(()=>{typeof browser<"u"&&!self.chrome&&(self.chrome=browser);(()=>{"use strict";let t,i,a=[],s=null,u=0,r={enabled:!0,size:8,duration:375,opacity:.25,color:"rgb(168 168 168)"},l={r:168,g:168,b:168},x=32,h=1e3/120;function E(e){let n=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(e);return n?{r:parseInt(n[1],16),g:parseInt(n[2],16),b:parseInt(n[3],16)}:{r:168,g:168,b:168}}function g(){chrome.storage.sync.get(r,e=>{w(e),r.enabled&&(y(),v())}),chrome.storage.onChanged.addListener((e,n)=>{if(n==="sync"){let o={};for(let c in e)o[c]=e[c].newValue;w(o)}})}function w(e){r={...r,...e},l=E(r.color),r.enabled&&!t?(y(),v()):!r.enabled&&t&&T(),t&&(t.style.opacity=r.opacity)}function y(){if(!t)try{if(t=document.createElement("canvas"),t.id="ripple-fx-canvas",t.style.cssText=`
          position: fixed !important;
          top: 0 !important;
          left: 0 !important;
          width: 100vw !important;
          height: 100vh !important;
          pointer-events: none !important;
          z-index: 2147483647 !important;
          opacity: ${r.opacity} !important;
          visibility: visible !important;
          display: block !important;
          transform: none !important;
        `,i=t.getContext("2d",{alpha:!0,desynchronized:!0}),!i)return;let e=document.body||document.documentElement;e.firstChild?e.insertBefore(t,e.firstChild):e.appendChild(t),m()}catch(e){console.warn("RippleFX: Init failed",e)}}function m(){if(!t||!i)return;let e=Math.max(document.documentElement.clientWidth||0,window.innerWidth||0),n=Math.max(document.documentElement.clientHeight||0,window.innerHeight||0),o=Math.min(2,window.devicePixelRatio||1);t.width=e*o,t.height=n*o,i.scale(o,o),t.style.width=e+"px",t.style.height=n+"px"}function R(e,n){!r.enabled||!i||(a.length>=x&&a.shift(),a.push({x:e,y:n,startTime:performance.now(),maxRadius:Number(r.size)}),s===null&&(u=performance.now(),s=requestAnimationFrame(p)))}function p(e){if(!i||!t)return;let n=e-u;if(n<h-1){s=requestAnimationFrame(p);return}u=e-n%h;let o=performance.now();i.clearRect(0,0,t.width,t.height);for(let c=a.length-1;c>=0;c--){let d=a[c],C=o-d.startTime,f=Math.min(C/Number(r.duration),1);if(f>=1){a.splice(c,1);continue}let M=1-Math.pow(1-f,3),F=d.maxRadius*M*2,L=1-f;i.beginPath(),i.arc(d.x,d.y,F,0,Math.PI*2),i.fillStyle=`rgba(${l.r}, ${l.g}, ${l.b}, ${L})`,i.fill()}a.length>0?s=requestAnimationFrame(p):s=null}function b(e){e.isTrusted&&R(e.clientX,e.clientY)}function v(){document.addEventListener("click",b,{passive:!0,capture:!0}),window.addEventListener("resize",m,{passive:!0})}function T(){s!==null&&(cancelAnimationFrame(s),s=null),t&&(t.remove(),t=null,i=null),a=[],document.removeEventListener("click",b,{capture:!0}),window.removeEventListener("resize",m)}document.readyState==="loading"?document.addEventListener("DOMContentLoaded",g,{once:!0}):g()})();})();
